# Generated by Django 3.2.9 on 2021-11-25 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_update_like_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
