# Generated by Django 3.2.9 on 2021-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211125_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(editable=False, max_length=500),
        ),
    ]
