# Generated by Django 3.2.8 on 2021-12-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211126_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_github',
            field=models.BooleanField(default=False),
        ),
    ]
