# Generated by Django 3.2.7 on 2021-10-29 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0019_rename_friend_request_to_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxobject',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
