# Generated by Django 3.2.7 on 2021-10-29 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0020_alter_inboxobject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
