# Generated by Django 3.2.9 on 2021-11-25 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0021_alter_follow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inboxobject',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inboxobject',
            name='object_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
