# Generated by Django 3.2.9 on 2021-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0022_auto_20211125_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(editable=False, max_length=500),
        ),
    ]
