# Generated by Django 3.2.8 on 2021-11-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0024_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
