# Generated by Django 3.2.7 on 2021-12-02 05:42

from django.db import migrations, models
from social_distance.utils import random_profile_color

def create_random_colors(apps, _):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Author = apps.get_model("authors", "Author")
    for author in Author.objects.all():
        author.profile_color = random_profile_color()
        author.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0025_alter_author_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_color',
            field=models.CharField(blank=True, default='#73B8FF', max_length=10, null=True),
        ),
        migrations.RunPython(create_random_colors),
    ]
