# Generated by Django 3.2.7 on 2021-12-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0026_author_is_internal'),
        ('authors', '0026_author_profile_color'),
    ]

    operations = [
    ]
