# Generated by Django 3.2.8 on 2021-11-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubEvent',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PushEvent', 'Push Event')], max_length=30)),
                ('github_username', models.CharField(max_length=40)),
                ('github_url', models.URLField()),
                ('event_content', models.TextField(default='', editable=False)),
                ('event_title', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
