# Generated by Django 3.2.8 on 2021-11-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubevent',
            old_name='github_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='githubevent',
            old_name='github_username',
            new_name='username',
        ),
    ]
