# Generated by Django 3.2.8 on 2021-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20211130_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubevent',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
