# Generated by Django 3.2.7 on 2021-10-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_needs_approval', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Dynamic Settings',
            },
        ),
    ]
