# Generated by Django 3.2.9 on 2021-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='host_url',
            field=models.URLField(max_length=500),
        ),
    ]
